### ISSUE TITLE
[FEATURE] GNB3: Group Screen

### ISSUE THREAD

**Issue by crolvlee** [IT-Cotato/9th-Squadus-FE#28]
## Description for development features
GNB3 그룹 화면 구현

## Todo-lists
**1. 헤더 - 다인**
- [x] 사용자가 속한 동아리 보여주는 UI
- [x] 사용자가 속한 동아리 API 연결
- [x] 탭바

**2. 기본정보 - 도현**
- [x] 기본 정보

**3. 일정 - 도현**
- [x] 일정

**4. 공지 - 다인**
- [x] 공지 메인 UI
- [x] 공지 불러오기 API 연결
- [x] 공지 상세 UI
- [x] 공지 상세 API 연결
- [x] 공지 작성 UI
- [x] 공지 작성 API 연결

**5. 회비 - 다인**
- [x] 회비 메인 UI
- [ ] 회비 메인을 위한 API 연결
- [x] 회비 등록 UI
- [ ] 회비 등록 API 연결
- [x] 회비 입금현황 UI
- [ ] 회비 입금현황 API 연결

**6. Main Navigation Bar - 다인**
- [x] Main Navigation Bar

## ETC
기타 사항
