### ISSUE TITLE
[FEATURE] GNB2: Promotion Screen

### ISSUE THREAD

**Issue by kdhqwe1030** [IT-Cotato/9th-Squadus-FE#66]
## Description for development features
교내 및 교외 동아리 홍보 게시글 페이지
## Todo-lists
- [ ] 필터 구현
- [ ] 헤더 구현
- [ ] 게시글 아이템 구현
- [ ] 교내 페이지 구현
- [ ] 교외 페이지 구현
- [ ] api연결

## ETC
기타 사항
