### ISSUE TITLE
[FEATURE] GNB1: Home Screen

### ISSUE THREAD

**Issue by leve68** [IT-Cotato/9th-Squadus-FE#7]
## Description for development features
홈 화면 구현

## Todo-lists
- [x] 캘린더 UI
- [ ] 캘린더 날짜 선택
- [ ] 일정 UI
- [x] 일정 데이터 표시
- [ ] 아티클 UI
- [ ] 상단 아티클 표시
- [ ] 하단 아티클 표시

## ETC
https://dnfldpden.atlassian.net/browse/JSGJ-14

**Comment by crolvlee** [comment]
이슈 삭제

**Comment by crolvlee** [comment]
이슈 삭제
